user:
    topic: usertopic
spring:
    kafka:
        bootstrap-servers: kafka:9092
        consumer:
            auto-offset-reset: earliest
            group-id: user-consumer-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer